
public class Caminhao extends Veiculo { //SUBCLASSE DA CLASSE PAI "veiculo"  //É NECESSARIO USAR O COMANDO "extends" PARA QUE ELA POSSA SE TORNAR UMA SUBCLASSE

	@Override
	public void buzinar() {
				System.out.println("FOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOM");
	}
	
	

}
